// <auto-generated />
namespace Test3_Bank.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addUserForignkeyToAccount1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addUserForignkeyToAccount1));
        
        string IMigrationMetadata.Id
        {
            get { return "201912090532514_addUserForignkeyToAccount1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
